// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function EnsureRuntimeReady() {
  return window['go']['main']['App']['EnsureRuntimeReady']();
}

export function GetDiagnosticsSnapshot() {
  return window['go']['main']['App']['GetDiagnosticsSnapshot']();
}

export function GetModelState(arg1) {
  return window['go']['main']['App']['GetModelState'](arg1);
}

export function GetTranscriptionSnapshot() {
  return window['go']['main']['App']['GetTranscriptionSnapshot']();
}

export function LoadModelSnapshot() {
  return window['go']['main']['App']['LoadModelSnapshot']();
}

export function LoadPreferences() {
  return window['go']['main']['App']['LoadPreferences']();
}

export function RetryTranscription() {
  return window['go']['main']['App']['RetryTranscription']();
}

export function SelectMediaFile() {
  return window['go']['main']['App']['SelectMediaFile']();
}

export function StartModelDownload(arg1) {
  return window['go']['main']['App']['StartModelDownload'](arg1);
}

export function StartTranscription(arg1) {
  return window['go']['main']['App']['StartTranscription'](arg1);
}

export function UpdatePreferences(arg1) {
  return window['go']['main']['App']['UpdatePreferences'](arg1);
}

export function ValidateMediaPath(arg1) {
  return window['go']['main']['App']['ValidateMediaPath'](arg1);
}
