// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';
import {transcription} from '../models';
import {settings} from '../models';
import {intake} from '../models';

export function DeleteModel(arg1:string):Promise<models.ModelStatus>;

export function EnsureRuntimeReady():Promise<main.RuntimeReadiness>;

export function GetDiagnosticsSnapshot():Promise<main.DiagnosticsSnapshot>;

export function GetModelState(arg1:string):Promise<models.ModelStatus>;

export function GetTranscriptionSnapshot():Promise<transcription.Snapshot>;

export function LoadModelSnapshot():Promise<models.Snapshot>;

export function LoadPreferences():Promise<settings.Preferences>;

export function RetryTranscription():Promise<transcription.Snapshot>;

export function SelectMediaFile():Promise<intake.MediaMetadata>;

export function StartModelDownload(arg1:string):Promise<models.ModelStatus>;

export function StartTranscription(arg1:main.transcriptionRequest):Promise<transcription.Snapshot>;

export function UpdatePreferences(arg1:settings.Preferences):Promise<settings.Preferences>;

export function ValidateMediaPath(arg1:string):Promise<intake.MediaMetadata>;
